### ISSUE TITLE
Audio selection not working with USB DAC

### ISSUE THREAD

**Issue by cravussin** [wackerl91/script.luna#108]
Hello,

On the latest stable release 0.6.3, my USB DAC isn't working when I select it from the GUI: upon launching moonlight I get an **ALSA error: -16**

Oddly, it did work a couple of times, but when I launched another game the error came back.

Here's the output from aplay -l

```
osmc@osmc:~$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Audio [SA9023 USB Audio], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Audio [SA9023 USB Audio], device 1: USB Audio [USB Audio #1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

```

Many thanks for your work.

**Comment by wackerl91** [comment]
@cravussin 
Thank you for your feedback!

Can you check if the expected device (i.e. the one you selected in the UI) is properly written to the config file produced by Luna? (It's usually in `~/.kodi/userdata/addondata/script.luna/.storage/luna.conf`)
Furthermore, does the UI show all devices, including both USB devices (similar to aplay's output)?

**Comment by wackerl91** [comment]
As always with issues that don't receive any more input, this is now closed as it can't be reproduced on my end.
Feel free to reopen it if the problem persists and more information can be shared.
