### ISSUE TITLE
XBox One S controller missing input

### ISSUE THREAD

**Issue by edalongeville** [wackerl91/script.luna#156]
- Luna Version: Latest
- nVidia GeForce Experience Version: Latest
- Moonlight Embedded Version: Latest
- OSMC Version: Latest

**Expected Behaviour:**
At the binding screen, the XBox One S Gamepad (bluetooth) should be able to bind all its keys.

**Actual Behaviour:**
When connected using bluetooth, Back and Home currently don't work. I don't know if this issue actually is caused by Luna, or if that's an OSMC problem.

**Comment by wackerl91** [comment]
Which binding screen? The one in OSMC / Kodi settings or the reaaaally dumbed down one in Luna?

If it's the latter: controller configuration in Luna is somewhat deprecated as moonlight-embedded got smarter a while back (see #152 ), so you shouldn't need to add any mapping files inside Luna.

In case it's the former: there's nothing I can do about it. If you can verify that it's the nice-looking configuration screen inside Kodi's settings either let the Kodi team or the OSMC team know.

**Comment by edalongeville** [comment]
Thanks for your answer. I meant kodi/osmc binding screen.

Looks like this is actually the wrong place to discuss it, as the issue seems to come from the bluetooth protocol, more specifically the way Kodi/OSMC interacts with the XBox One S controller.

Sorry for the mistake, and thanks a lot for your work on luna!
