### ISSUE TITLE
Wireless Xbox 360 Controller doesn't connect anymore

### ISSUE THREAD

**Issue by LevanKujak** [wackerl91/script.luna#163]
- Luna Version: 0.7
- nVidia GeForce Experience Version: 3.11.0.73
- Moonlight Embedded Version: i will provide later (i think newest)
- OSMC Version: 10-2017

**Expected Behaviour:** The first time i used the wireless controller they worked without a problem (only while streaming a game or steam tho not in luna or osmc what i don't need). Then i made an OSMC update and now the controller doesn't connect anymore to his wireless receiver.

It connected in Luna/OSMC first and didn't work there when i pushed buttons but while streaming worked fine - now it doesn't even connect anymore.

**Actual Behaviour:** Controller doesn't connect to his wireless receiver can't use it while streaming.

I don't know if that belongs to moonlight or in here - if i am wrong pls say so and i will there submit that issue.

**Comment by wackerl91** [comment]
Likely either OSMC or hardware proiblem. A controller not connecting to its receiver is not an issue Luna could induce (or solve, for that matter).
