### ISSUE TITLE
Add host doesn't do anything

### ISSUE THREAD

**Issue by rjayyyy** [wackerl91/script.luna#169]
- Luna Version: Luna 0.7.0-rc7
- nVidia GeForce Experience Version: 3.15.0.186
- Moonlight Embedded Version: v0.6.2
- OSMC Version: - Running Windows, can this launcher be used on Windows with Kodi?

**Expected Behaviour:**

**Actual Behaviour:**
Luna installs correctly and I can access the settings menu but clicking add host nothing happens. Clicking the other two menu options produces an exception. Launch Moonlight itself, from GUI or commandline works fine. Is this able to be used from Windows, am I missing something?

thanks

**Comment by Pawe98** [comment]
It probably won't work in windows as Linux bash syntax is used, you would need to rewrite bash code to windows commandline or powershell. But why would you like to use then Luna launcher when moonlight as a UI in Windows that also supports gamepad input?

Alternative 1:You could checkout cygwin and the stuff mentioned in the approved answer from here:
https://stackoverflow.com/questions/26522789/how-to-run-sh-on-windows-command-prompt

Alternative 2:You could run OSMC on a Linux distro in a virtual machine

**Comment by rjayyyy** [comment]
Thanks for the response Pawe98. Makes sense and was what I figured at the time. I was just trialing some in house streaming methods and while this was a fair while back now I think it was the simplicity of interface that I preferred. thanks

**Comment by OneCricketeer** [comment]
Also #164

**Comment by wackerl91** [comment]
I'll close this, as Luna isn't expected to work an Windows as @Pawe98 already said.
(Sorry for pinging you guys for a "dead" issue ... )
